---
 SWEs-dc1-edge17:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge17.acme.com
 SWEs-dc1-edge18:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge18.acme.com
 SWEs-dc1-edge19:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge19.acme.com
 SWEs-dc1-edge20:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge20.acme.com
 SWEs-dc1-edge21:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge21.acme.com
 SWEs-dc1-edge22:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge22.acme.com
 SWEs-dc1-edge23:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge23.acme.com
 SWEs-dc1-edge24:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge24.acme.com
 SWEs-dc1-edge25:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge25.acme.com
 SWEs-dc1-edge26:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge26.acme.com
 SWEs-dc1-edge27:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge27.acme.com
 SWEs-dc1-edge28:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge28.acme.com
 SWEs-dc1-edge29:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge29.acme.com
 SWEs-dc1-edge30:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge30.acme.com
 SWEs-dc1-edge31:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge31.acme.com
 SWEs-dc1-edge32:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge32.acme.com
 SWEs-dc1-edge33:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge33.acme.com
 SWEs-dc1-edge34:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge34.acme.com
 SWEs-dc1-edge35:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge35.acme.com
 SWEs-dc1-edge36:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge36.acme.com
 SWEs-dc1-edge5:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge5.acme.com
 SWEs-dc1-edge6:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge6.acme.com
 SWEs-dc1-edge7:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge7.acme.com
 SWEs-dc1-edge8:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge8.acme.com
 SWEs-dc1-edge9:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge9.acme.com
 SWEs-dc1-edge10:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge10.acme.com
 SWEs-dc1-edge13:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge13.acme.com
 SWEs-dc1-edge14:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge14.acme.com
 SWEs-dc1-edge15:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge15.acme.com
 SWEs-dc1-edge16:
   groups:
   - nxos_devices
   hostname: SWEs-dc1-edge16.acme.com
 SWEs-dc2-edge17:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge17.acme.com
 SWEs-dc2-edge18:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge18.acme.com
 SWEs-dc2-edge19:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge19.acme.com
 SWEs-dc2-edge20:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge20.acme.com
 SWEs-dc2-edge21:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge21.acme.com
 SWEs-dc2-edge22:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge22.acme.com
 SWEs-dc2-edge23:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge23.acme.com
 SWEs-dc2-edge24:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge24.acme.com
 SWEs-dc2-edge25:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge25.acme.com
 SWEs-dc2-edge26:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge26.acme.com
 SWEs-dc2-edge27:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge27.acme.com
 SWEs-dc2-edge28:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge28.acme.com
 SWEs-dc2-edge29:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge29.acme.com
 SWEs-dc2-edge30:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge30.acme.com
 SWEs-dc2-edge31:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge31.acme.com
 SWEs-dc2-edge32:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge32.acme.com
 SWEs-dc2-edge33:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge33.acme.com
 SWEs-dc2-edge34:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge34.acme.com
 SWEs-dc2-edge35:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge35.acme.com
 SWEs-dc2-edge36:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge36.acme.com
 SWEs-dc2-edge5:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge5.acme.com
 SWEs-dc2-edge6:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge6.acme.com
 SWEs-dc2-edge7:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge7.acme.com
 SWEs-dc2-edge8:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge8.acme.com
 SWEs-dc2-edge9:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge9.acme.com
 SWEs-dc2-edge10:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge10.acme.com
 SWEs-dc2-edge13:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge13.acme.com
 SWEs-dc2-edge14:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge14.acme.com
 SWEs-dc2-edge15:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge15.acme.com
 SWEs-dc2-edge16:
   groups:
   - nxos_devices
   hostname: SWEs-dc2-edge16.acme.com
